[package]
name = "dinner-party"
version = "0.1.0"
edition = "2024"

[lib]
name = "dinner_party"
path = "src/lib.rs"
edition = "2024"

[dependencies]
argmin = { version = "0.10.0", features = ["rayon"] }
clap = { version = "4.5.31", features = ["derive"] }
csv = "1.3.1"
rand = "0.9.0"
